### ISSUE TITLE
Crash for missing translation strings

### ISSUE THREAD

**Issue by Maybach91** [Shopify/theme-check#595] opened 2022-06-20 15:56 UTC
I think its because i didn’t add all new translation strings to all possible translation files. I’m only using DE + EN. 

Command i ran:  
 `shopify theme check --auto-correct`
<details>
<summary>Show Terminal Output</summary>

```zsh
 Theme check failed with error:
┃ /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/bug.rb:20:in `bug': Exception while running `Offense#correct`: (ThemeCheck::ThemeCheckError)
┃ ```
┃ IndexError: string not matched
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:10:in `[]='
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:10:in `block in set'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each_with_index'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `reduce'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `set'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/corrector.rb:54:in `add_translation'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:63:in `block (2 levels) in add_missing_keys_offense'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:62:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:62:in `block in add_missing_keys_offense'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/offense.rb:149:in `correct'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `each'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `correct_offenses'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:192:in `check'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command.rb:27:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:49:in `block in <top (required)>'
┃   /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:59:in `<top (required)>'
┃   /opt/homebrew/bin/shopify:8:in `load'
┃   /opt/homebrew/bin/shopify:8:in `<main>'
┃ ```
┃ 
┃ Offense:
┃ ```
┃ {
┃   "check": "MatchingTranslations",
┃   "path": "locales/bg-BG.json",
┃   "severity": 1,
┃   "start_row": 0,
┃   "start_column": 0,
┃   "end_row": 0,
┃   "end_column": 0,
┃   "message": "Missing translation keys: newsletter.success.title, newsletter.success.text, newsletter.error, newsletter.already_subscribed, newsletter.subtext, accessibility.more_loading, blogs.article_count, blogs.article.ingredients, blogs.article.instructions, blogs.article.summary, blogs.article.suitablefor, blogs.article.relatedrecipes, blogs.article.relatedposts, blogs.article.cookingtime, blogs.article.preparationtime, blogs.article.duration, blogs.article.portions, products.product.new, products.product.stock_label, products.product.preorder, products.product.will_not_ship_until, products.product.will_be_in_stock_after, products.product.waiting_for_stock, products.product.taxes_included_and_shipping_policy, products.product.diet_disclaimer, products.product.nutrient_data, products.product.general_information, products.product.diet, products.product.ingredients, products.product.reviews, products.product.no-reviews, products.product.additional-information, products.product.product-faq-headline, products.product.related_recipes, sections.cart.show, sections.cart.recommendations, sections.cart.free_shipping_on_html, sections.cart.free_shipping_html, sections.footer.reviews, sections.collection_list.load_prev, sections.collection_list.load_more, sections.collection_list.more_loading, sections.collection_list.collection_loading"
┃ }
┃ ```
┃ Check options:
┃ ```
┃ {}
┃ 
┃ ```
┃ Markup:
┃ ```
┃ 
┃ ```
┃ Node.Markup:
┃ ```
┃ 
┃ ```
┃ Theme Check Version: 1.10.3
┃ Ruby Version: 3.1.2
┃ Platform: arm64-darwin21
┃ Muffin mode: activated
┃ 
┃ ------------------------
┃ Whoops! It looks like you found a bug in Theme Check.
┃ Please report it at https://github.com/Shopify/theme-check/issues, and include the message above.
┃ Or cross your fingers real hard, and try again.
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/offense.rb:152:in `rescue in correct'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/offense.rb:146:in `correct'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `each'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `correct_offenses'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:192:in `check'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command.rb:27:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:49:in `block in <top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:59:in `<top (required)>'
┃ 	from /opt/homebrew/bin/shopify:8:in `load'
┃ 	from /opt/homebrew/bin/shopify:8:in `<main>'
┃ /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:10:in `[]=': string not matched (IndexError)
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:10:in `block in set'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each_with_index'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `each'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `reduce'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/schema_helper.rb:8:in `set'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/corrector.rb:54:in `add_translation'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:63:in `block (2 levels) in add_missing_keys_offense'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:62:in `each'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/locale_diff.rb:62:in `block in add_missing_keys_offense'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/offense.rb:149:in `correct'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `each'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/analyzer.rb:118:in `correct_offenses'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:192:in `check'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/theme-check-1.10.3/lib/theme_check/cli.rb:123:in `run!'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/project_types/theme/commands/check.rb:27:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command/sub_command.rb:16:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/command.rb:27:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:16:in `block in call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/executor.rb:15:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:24:in `block in call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/monorail.rb:26:in `log'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/lib/shopify_cli/core/entry_point.rb:23:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:50:in `block (2 levels) in <top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:49:in `block in <top (required)>'
┃ 	from /opt/homebrew/Cellar/shopify-cli/2.19.0/gems/shopify-cli-2.19.0/bin/shopify:59:in `<top (required)>'
┃ 	from /opt/homebrew/bin/shopify:8:in `load'
┃ 	from /opt/homebrew/bin/shopify:8:in `<main>'
┃ 

```
</details>

**Comment by Mim-Jones** [comment] 2022-07-05 11:07
I have the same issue any chance you were you able to resolve it? @Maybach91

**Comment by Mim-Jones** [comment] 2022-07-05 11:54
Update for anyone else working on this. I manually fixed all the translation strings and the issue persists

**Comment by charlespwd** [comment] 2022-07-11 14:53
Closing as duplicate of #585

**Closed by charlespwd** 2022-07-11 14:53 UTC
