### ISSUE TITLE
Error: Asset should be served by the Shopify CDN for better performance

### ISSUE THREAD

**Issue by techtastet** [Shopify/theme-check#366] opened 2021-07-15 08:33 UTC
Hi again!

"theme check" returns an error on my "theme.liquid" at the DOM definition level, telling me that I have assets that are not served by the Shopify CDN, except that all are.

In the second screenshot, I have 3 JS scripts well imported with Shopify CDN and when I remove them from my code, the error disappears, so I conclude that it's those script tags that are giving the error.

![Capture d’écran 2021-07-15 à 10 30 35](https://user-images.githubusercontent.com/31560900/125755860-51d13241-5aa3-4ed1-abaf-324f5c637968.png)
![Capture d’écran 2021-07-15 à 10 30 54](https://user-images.githubusercontent.com/31560900/125755916-ec7a186f-c261-4e10-add8-483bdf9c8a28.png)

**Comment by charlespwd** [comment] 2021-07-15 13:35
Hiya :wave: thanks for the report!

Closing since this is a duplicate of #362.

In the meantime this can be fixed by switching quote type in/out of attributes. Our HTML parser doesn't know about liquid so as soon as it sees another `"` it thinks that's the end of the HTML attribute.

**Closed by charlespwd** 2021-07-15 13:35 UTC
