### ISSUE TITLE
Snippet variables incorrectly throwing warnings

### ISSUE THREAD

**Issue by Eben-Hafkamp** [Shopify/theme-check#173] opened 2021-02-21 21:49 UTC
Vars used inside of rendered snippets are being flagged as having not been assigned.

**Comment by charlespwd** [comment] 2021-02-22 14:21
Is this a duplicate of #159 ? If so, this looks like #160 is a fix for this. The fix is in 0.3.2

**Comment by macournoyer** [comment] 2021-02-24 18:09
`brew upgrade theme-check` should fix it. Feel free to re-open if not.

**Closed by macournoyer** 2021-02-24 18:09 UTC
